services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    networks:
      - fastapi_network

  db:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
      - "5432:5432"
    networks:
      - fastapi_network

  migrator:
    build: .
    command: ./migration_script.sh
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network:
    driver: bridge